name: Tests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Verify
        run: make

      - name: Set up static analysis
        run: |
          sudo apt update
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check test coverage
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/org/project
          threshold-file: 100
          threshold-package: 100
          threshold-total: 100

      - name: Make coverage badge
        uses: action-badges/core@0.2.2
        if: contains(github.ref, 'main')
        with:
          label: Coverage
          message: ${{ steps.coverage.outputs.badge-text }}
          message-color: ${{ steps.coverage.outputs.badge-color }}
          file-name: coverage.svg
          badge-branch: badges
          github-token: "${{ secrets.GITHUB_TOKEN }}"
